In [32]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
#Hi

In [33]:
# !pip install pydub

In [34]:
# from google.colab import drive
# drive.mount('/content/drive')

INDEX -6


# **Creating Arrays**

#### 1. Create a 1D array with 20 random integers between 1 and 100.
**Hint:** Use the `np.random.randint()` function, specifying the range and size.
#### 2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.
#### 3. Create a diagonal matrix with values `[1, 2, 3, 4]` on the diagonal.
#### 4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.
**Hint:** Use `np.tile()` to repeat arrays along rows or columns.
#### 5. Create a 1D array with alternating 0s and 1s of length 10.
#### 6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to `int32`.

In [35]:
a=np.random.randint(1,100,size=20)
print(a)

[61 65 56  9 31 64  8  6 39 77 63 68 15  8 28 78 86 34 52 70]


In [36]:
#5x5 border 1 inner 0
a=np.ones((5,5),dtype=np.int32)
a[1:4,1:4]=0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [37]:
a=np.diag([1,2,3,4])
print(a)#diagflat

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [38]:
a=np.tile([1,2,3],(3,1))
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
a=np.tile([0,1],5)
print(a)

[0 1 0 1 0 1 0 1 0 1]


In [40]:
b=np.random.randint(10,20,size=(3,3),dtype=np.int32)
print(b,b.dtype)

[[18 10 17]
 [13 19 16]
 [16 14 17]] int32


# **Array Attributes**

####1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:

  1. shape of the array
  2. size of the array
  3. number of dimensions
  4. data type

####2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.
Test the function with the following arrays:

  1. A 1D array with 5 elements.
  2. A 2D array of size (3x4).
  3. A 3D array of size (2x3x4).


####3. ***Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.*** (doubt)

####4. Write a Python function that:
  1. Creates a 6×3 array of integers using NumPy.
  2. Prints the shape of the array using the shape attribute.
  3. Reshapes the array to 3×6 and prints the new shape.



####5. Write a program to:
  1. Create an array of any size with all elements being 0 and use the appropriate attribute to print the size (in bytes) of each element in the array.
  2. Create an array of any size with elements between 1 to 10 and print the size.
  3. Create another array with floating-point numbers of any size and observe how the size changes.



In [41]:
a=np.random.randint(1,10,size=(4,5))
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[[3 9 1 9 6]
 [7 5 5 2 5]
 [9 6 9 8 2]
 [3 1 6 9 9]]
(4, 5)
20
2
int32


In [42]:
a=np.zeros(5)
b=np.zeros((3,4))
c=np.zeros((2,3,4))
print(a.ndim,b.ndim,c.ndim)

1 2 3


In [43]:
a=np.random.randint(0,10,12,dtype=np.int32)
print(a,a.dtype)
a=np.float32(a)
print(a,a.dtype)
# a=np.array_str(a)# array2string

a=[str(i) for i in a]
a=np.array(a)

print(a,a.dtype)
# print(a)

[2 6 7 7 6 7 4 0 0 5 9 7] int32
[2. 6. 7. 7. 6. 7. 4. 0. 0. 5. 9. 7.] float32
['2.0' '6.0' '7.0' '7.0' '6.0' '7.0' '4.0' '0.0' '0.0' '5.0' '9.0' '7.0'] <U3


In [44]:
a=np.random.randint(1,25,size=(6,3))
print(a,"\n",a.shape)
a=a.reshape(3,6)
print(a,"\n",a.shape)

[[15  4  1]
 [23  1  9]
 [13 20 20]
 [18  4 13]
 [22 10 17]
 [ 4  6  3]] 
 (6, 3)
[[15  4  1 23  1  9]
 [13 20 20 18  4 13]
 [22 10 17  4  6  3]] 
 (3, 6)


In [45]:
a=np.zeros((4,5),dtype=np.int32)
print(a.itemsize,a)

a=np.arange(2,10)
print(a.size,a)

a=np.zeros((4,5),dtype=np.float64)
print(a.itemsize,a)

4 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
8 [2 3 4 5 6 7 8 9]
8 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# **Sorting and Partioning**

####1. Given an array arr, sort the array in ascending order without modifying the original array. Print both the original and sorted arrays.(use np.sort())

####2. You have arr = np.array([50, 30, 40, 20]) and names = np.array(["A", "B", "C", "D"]).
Sort the arr values in ascending order and rearrange the names array accordingly.(use np.argsort() to get sorted indices and reorder names)

####3. Write code to find the k smallest elements from the array arr. Print these elements in ascending order.(use np.partition())

####4. Partition the array arr such that all elements smaller than a particular number(user input) appear before those greater than or equal to that number. Print the partitioned array.(use np.partition() to find the pivot value's index)

####5. Sort each row of a 2D array arr in ascending order.(use np.sort() with axis parameter)

####6. Print k largest elements of an array arr in descending order.(use np.partition() to find top k elements)

####7. Given an array arr(containing possible negative values), sort the array in ascending order based on the absolute values of the elements. Print the sorted array.(use np.argsort() with a custom key for absolute values)

####8. Given an array arr, sort only the elements greater than k in ascending order, keeping the other elements in their original positions.(create a mask to find elements greater than k, use np.sort() to sort them then reassign the sorted values back to their original indices in the array)

In [46]:
a=np.random.randint(1,20,size=10)
b=np.sort(a)
print(a,b)

[19  6 18  6  9 17 10 14  1 10] [ 1  6  6  9 10 10 14 17 18 19]


In [47]:
arr=np.array([50,30,40,20])
names=np.array(["a","b","c","d"])
b=np.argsort(arr)

print(arr[b],names[b])

[20 30 40 50] ['d' 'b' 'c' 'a']


In [48]:
a=np.random.randint(0,25,25)#.sort()
k=5
b=np.partition(a,k)[:k]
for i in range(k-1,-1):
    b=np.partition(b,i)
print(b)

[0 1 1 1 2]


In [49]:
arr = np.array([8,5,3,1,4])
k=int(input())
idx=0
for i in range(0,len(arr)):
    if arr[i]<k:
        idx+=1
b=np.partition(arr,idx)
print(b)

[1 3 4 5 8]


In [50]:
a=np.random.randint(1,25,size=(7,8))
a.sort(axis=1)
print(a)

[[ 1  1  1  1  5  5 10 23]
 [ 4  5  8  9 11 14 19 20]
 [ 3  6 12 12 18 20 20 23]
 [ 4  6  8 16 16 19 21 23]
 [ 7  8  8 16 16 18 19 20]
 [ 4  6  6  8  9 17 21 21]
 [ 1  6  7  9 18 22 23 23]]


In [51]:
a=np.random.randint(0,25,25)
k=5
b=np.partition(a,len(a)-k)[len(a)-k :]
print(a)
print(b)

[10 14  0 23  5 23 16  4 10 17 10  1  9  1 10  6 10 10 19 19 12 17 18 19
  6]
[19 19 19 23 23]


In [52]:
a=np.random.randint(-10,10,size=12)
print(a)

# b=np.array(sorted(a,key=lambda x:abs(x)))
# print(b)

idx=np.argsort(np.abs(a))
print(a[idx])

[ 4 -2  2  1 -9 -1  4 -4  8  0  0 -1]
[ 0  0  1 -1 -1  2 -2  4  4 -4  8 -9]


In [53]:
arr=np.array([3,7,2,1,8,6,4])# 3 6 2 1 7 8 4
k=5
mask=arr>k
arr[mask]=np.sort(arr[mask])
arr

array([3, 6, 2, 1, 7, 8, 4])

# **Indexing and slicing**

#### 1. 2D Array Indexing
Consider the following 2D array:
`arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`
- Access the element at row index 1 and column index 2.
- Extract the first row.
- Extract the last column.

In [54]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(arr_2d[1,2])
print(arr_2d[0,:])
print(arr_2d[:,2])

30
[ 5 10 15]
[15 30 45]


#dd

#### 2. Boolean Indexing
Given an array `arr = np.array([2, 5, 8, 11, 14, 17, 20])`, use boolean indexing to:
- Extract all values greater than 10.
- Replace all values greater than 15 with -1.

In [55]:
arr = np.array([2, 5, 8, 11, 14, 17, 20])
mask=arr>10
mask2=arr>15
print(arr[mask])
arr[mask2]=-1
print(arr)

[11 14 17 20]
[ 2  5  8 11 14 -1 -1]


#### 3. Fancy Indexing
Using the 2D array `arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`, write code to:

- Select the elements at positions (0,2), (1,1), and (2,0).
- Use fancy indexing to create a submatrix with rows 0 and 2, and columns 1 and 2.

- **Hint:**
 - For 1st part, use arrays of row and column indices
 - For 2nd part, you can create a submatrix using fancy indexing by using np.newaxis to match the dimensions


In [56]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
# print(arr_2d)

print(arr_2d[[0,1,2],[2,1,0]])
row_array=np.array([0,2])
col_array=np.array([1,2])
#why not b=arr_2d[row_array,col_array]
b=arr_2d[row_array,1:3]
print(b)

[15 25 35]
[[10 15]
 [40 45]]


#### 4. Slicing 1D array
Given the array `arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])`, write code to:

- Extract the first 4 elements.
- Extract every second element from the entire array.
- Extract elements from index 2 to the end, stepping by 2.

In [57]:
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])
a=arr[:4]
b=arr[::2]
c=arr[2::2]
print(a,b,c)

[1 3 5 7] [ 1  5  9 13] [ 5  9 13]


#### 5. Slicing a 2D Array
Given the following 2D array:
`arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])`
- Slice and print the last two columns of 1st row.
- Slice and print the last row, reversed.

In [58]:
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print(arr_2d[0,[2,3]])
print(arr_2d[2][::-1])

[30 40]
[120 110 100  90]


#### 6. Handling Out-of-Range Indices in Slicing vs. Indexing
Given the array:
`arr = np.array([10, 20, 30, 40, 50])`


- What will be the output of the following slicing operations? Explain why they work, even though some indices are out of range.
 - print(arr[2:10])  
 - print(arr[-10:3])    

- Compare the behavior of slicing to accessing a single element with an out-of-range index (e.g., arr[10]). Why does slicing not raise an error in these cases, but indexing does?

[30,40,50]
[10,20,30]

1)This happens as slicing starts from starting index 2 and the compiler sees that the index is > than len(arr)-1 so it auto assigns the index to end of array.
 In the second case compiler sees index is less than -(len(arr)) it assigns the index to start of array


2)When a single element is accessed



#### 7.  Work with an Audio File

Download the audio file from the following link: Simple Logo - Pixabay. Load the audio file using pydub and complete the following tasks:

- Extract the first second of the audio and plot its waveform.
   - Hint: Use the frame rate to calculate how many samples are in 1 second, and use slicing to extract this part.

-   Extract the last second of the audio and plot its waveform.
  

-  Combine the samples from the first second and the last second into a new array and plot the combined waveform.
 - Hint: Use NumPy’s np.concatenate() function to merge the two slices.

In [ ]:
from pydub import AudioSegment

audio_path = "/content/drive/MyDrive/Colab Notebooks/simple.mp3"

audio = AudioSegment.from_mp3(audio_path)
audio= audio.set_channels(1)
audio_arr = np.array(audio.get_array_of_samples())
print(audio.duration_seconds)
onesec=audio.frame_rate


time = np.linspace(0, len(audio_arr) / audio.frame_rate, num=len(audio_arr))
plt.plot(time, audio_arr)
plt.xlabel("Time")
plt.show()


time = np.linspace(0, 1, num=int(audio.frame_count(1000)))
first_sec=audio_arr[:onesec]
plt.plot(time,first_sec)
plt.xlabel("Time")
plt.show()

last_sec=audio_arr[-onesec:]
plt.plot(time,last_sec)
plt.xlabel("Time")
plt.show()


time = np.linspace(0, 2, num=int(audio.frame_count(2000)))
plt.plot(time,np.concatenate((first_sec,last_sec)))
plt.xlabel("Time")
plt.show()


# **Reshaping in NumPy**


####1. Create a 2D array of shape (3, 5). Flatten it into a 1D array and then reshape it back into a (5, 3) array.

####2. Create a 1D array
```
arr = np.array([1, 2, 3, 4, 5])
```
####Reshape arr into (5,1), then convert to (5,) and then convert it into (1,5).


####3. Create a 1D NumPy array with values ranging from 1 to 100. Reshape it into a (10, 10) matrix. Apply '.ravel()' and '.flatten()' on the matrix and modify the original matrix. Compare the outputs of both methods and explain the difference in memory sharing.


####4. Generate a 5x5 NumPy matrix representing pixel intensities from an image. Use slicing to extract the central 3x3 section of the matrix and flatten it. How does reshaping impact the spatial relationships of the pixels?


####5. Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4) with random integer values between 0 and 255. Flatten the image using '.reshape()' and reshape it back to its original shape. Explain the order of pixel data stored and how reshaping affects the channel structure.



In [60]:
a=np.random.randint(1,25,size=(3,5))
print(a)
a=a.flatten()
print(a)
a=a.reshape(5,3)
print(a)

[[14  4 11  9 18]
 [24 23  4 10 20]
 [15  1 21 16  3]]
[14  4 11  9 18 24 23  4 10 20 15  1 21 16  3]
[[14  4 11]
 [ 9 18 24]
 [23  4 10]
 [20 15  1]
 [21 16  3]]


In [61]:
arr = np.array([1, 2, 3, 4, 5])
arr=arr.reshape(5,1)
print(arr)
arr=arr.reshape(5,)
print(arr)
arr=arr.reshape(1,5)
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


In [62]:
arr_1d = np.arange(1,101)
matrix = arr_1d.reshape(10, 10)

arr = matrix.ravel()
print("Ravel Array:", arr)

arr = matrix.flatten()
print("Flatten Array:", arr)


# .ravel() returns a view of the original array ie.the same memory.
# So, modifying the original matrix also changes the ravel array.

# .flatten() returns a copy of the original array, so changes to the original do not affect it.

Ravel Array: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Flatten Array: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [63]:
np.random.seed(seed=42)
imArr=np.random.randint(0,255,size=(5,5))

print(imArr)

a=imArr[1:4,1:4].flatten()

print(a)

#The spatial arrangement of the data of the image changes .The data about spatial orientation of the pixels of the image is lost .
#But if you know thw way the array has been flattened you can retrieve the original array back
# eg to get original array back in np.flatten you can you reshape back to its original shape.
# This works as both of them uses C-style to flatten and reshape


[[102 179  92  14 106]
 [ 71 188  20 102 121]
 [210 214  74 202  87]
 [116  99 103 151 130]
 [149  52   1  87 235]]
[188  20 102 214  74 202  99 103 151]


In [64]:
image = np.random.randint(0, 256, (3, 4, 4), dtype=np.int16)
print("Original image ", image,'\n')

flattened_image = image.flatten()
print("Flattened image :", flattened_image,'\n')

reshaped_image = flattened_image.reshape(3, 4, 4)
print("Reshaped image data:", reshaped_image,'\n')

# When you flatten the data ,the data values of the Red appears first in the flattened array then Green and then Blue.
# When you shape it original position and shape of all the pixel is brought back as both flatten and reshape by default follow "C-order"


Original image  [[[157  68  37  91]
  [129  51 191 140]
  [187   1  20 243]
  [160  19 203 226]]

 [[ 57 149  21  86]
  [252 207 235 147]
  [ 88 231  48 141]
  [218  87  58 162]]

 [[254  93 169 181]
  [255 242 219 201]
  [187  72 207 201]
  [ 14 150 189 193]]] 

Flattened image : [157  68  37  91 129  51 191 140 187   1  20 243 160  19 203 226  57 149
  21  86 252 207 235 147  88 231  48 141 218  87  58 162 254  93 169 181
 255 242 219 201 187  72 207 201  14 150 189 193] 

Reshaped image data: [[[157  68  37  91]
  [129  51 191 140]
  [187   1  20 243]
  [160  19 203 226]]

 [[ 57 149  21  86]
  [252 207 235 147]
  [ 88 231  48 141]
  [218  87  58 162]]

 [[254  93 169 181]
  [255 242 219 201]
  [187  72 207 201]
  [ 14 150 189 193]]] 



# **Universal Functions**

Q1) Given an array x = [1, 4, 9, 16, 25], compute the square root of each element in the array and print the result.

Q2) Create an array angles =[0, $\frac{\pi}{2}$, $\pi$, $\frac{3\pi}{2}$]
, calculate the sine of each angle and print the result.



Q3) Given two arrays a =[True, False, True] and b = [False, False, True], perform an element-wise logical AND operation and print the result.

Q4) Create two arrays x = [1, 2, 3, 4] and y = [2, 2, 3, 5], perform an element-wise comparison (x < y) and print the result.

Q5) Create an array x =[-2, -1, 0, 1, 2, 3, 4], compute the following element-wise operation:

* If an element is negative, square it.
* If an element is non-negative, compute its exponential.
Print the resulting array.

In [65]:
x=np.array([1,4,9,16,25])
print(np.sqrt(x))

[1. 2. 3. 4. 5.]


In [66]:
angles=np.array([0,np.pi/2,np.pi,3*np.pi/2])
print(np.sin(angles))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


In [67]:
a=np.array([True,False,True])
b=np.array([False,False,True])
c=np.logical_and(a,b)
print(c)

[False False  True]


In [68]:
x=np.array([1,2,3,4])
y=np.array([2,2,3,5])
mask=y>x
print(mask)

[ True False False  True]


In [69]:
x=np.array([-2, -1, 0, 1, 2, 3, 4]).astype(np.float32)
mask=x<0
x[mask]=np.square(x[mask])

x[np.logical_not(mask)]=np.exp(x[np.logical_not(mask)])
print(x,x.dtype)

[ 4.         1.         1.         2.718282   7.3890557 20.085537
 54.59815  ] float32


# **Aggregations**


####1. Generate a random array of size 10.
 calculate the following:
- Print the array
- The sum of all elements.
- The mean of the array.
- The standard deviation.
- Find 5$*$Minimum -3$*$Maximum

####2. Generate a 4x5 matrix with random integers between 1 and 50.
- Print the matrix.
- Compute the mean of all elements in the matrix.
- Compute the sum of each row in the matrix.

####3. Generate a random 3x3 matrix with random integers between 1 to 10
- Find the minimum value in each column and store it in a separate list min.
- Find the maximum value in each row and store it in a separate list max.
- Find the value of minimum of list max - maximum of list min.

####4. Given the array : data = np.array([15, 25, 35, 45, 55, 65]):
- Find the minimum value.
- Subtract this minimum value from all elements of the array and then calculate the mean of the resulting array.

####5. Given the array : arr = np.array([3, 5, 7, 9, 11]):
- Compute the cumulative sum of the elements.
- Compute the cumulative product of the elements.

####6. Imagine you have a dataset representing the scores of 4 students in 3 subjects:
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
- Compute the average score for each student.
- Compute the highest score in each subject.
- Determine the overall average score for all students across all subjects.

In [70]:
arr=np.random.randint(1,25,size=10)
sum=np.sum(arr)
mean=np.mean(arr)
std=np.std(arr)
ans=5*arr.min()-3*arr.max()
print("arr:",arr)
print("sum:",sum)
print("mean:",mean)
print("std:",std)
print("ans:",ans)

arr: [15 19 12 23 20  3  5 19  7 21]
sum: 144
mean: 14.4
std: 6.8585712797928995
ans: -54


In [71]:
arr=np.random.randint(1,50,size=(4,5))
print(arr)

mean=np.mean(arr)
print(mean)

sums=np.sum(arr,axis=1)
print(sums)

[[ 9 39 18  4 25]
 [14  9 26  2 20]
 [28 47  7 44  8]
 [47 35 14 17 36]]
22.45
[ 95  71 134 149]


In [72]:
arr=np.random.randint(1,15,size=(3,3))
minCol=np.min(arr,axis=0)
maxRow=np.max(arr,axis=1)
ans=np.min(maxRow)-np.max(minCol)
print(arr)
print("list min:",minCol)
print("list max:",maxRow)
print("Ans:",ans)

[[ 2  8  4]
 [ 2 14  6]
 [ 6 10  4]]
list min: [2 8 4]
list max: [ 8 14 10]
Ans: 0


In [73]:
data = np.array([15, 25, 35, 45, 55, 65])
print(data)
minVal=np.min(data)
print(minVal)
mean=np.mean(data-minVal)
print(mean)

[15 25 35 45 55 65]
15
25.0


In [74]:
arr = np.array([3, 5, 7, 9, 11])
cSum=np.cumsum(arr)
cProd=np.cumprod(arr)
print(cSum)
print(cProd)

[ 3  8 15 24 35]
[    3    15   105   945 10395]


In [75]:
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
studAvg=np.average(scores,axis=1)
maxScore=np.max(scores,axis=1)
Average=np.average(scores)
print("Stud Avg:",studAvg)
print("Max Score of Stud:",maxScore)
print("Avg Marks:",Average)


Stud Avg: [85.         86.33333333 87.33333333 82.66666667]
Max Score of Stud: [92 95 91 88]
Avg Marks: 85.33333333333333


# **Broadcasting in NumPy**



####1. Given two arrays:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) (shape: (3, 3))
B = np.array([10, 20, 30]) (shape: (3,))
Perform elementwise addition of A and B using broadcasting and print the result.

What is the resulting shape?





####2. Write a function check_broadcasting(shape1, shape2) that:

Accepts two shapes as input and checks if they are broadcast-compatible.
Use the function to test the following shape pairs:
(3, 4) and (4,)
(2, 1, 5) and (3, 5)
(2, 3) and (2,)

For each case:

* State whether broadcasting is possible.

* If possible, state the resulting shape of the operation

####3. Create a 2D array A of shape (3, 5) with random integers between 1 and 10.
Create a 1D array B of shape (5,) with random integers between 1 and 5.
Use broadcasting to subtract B from each row of A and print the result.

####4.  Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10.

* Create an array B of shape (4, 3) containing a constant value of 5.
* Use broadcasting to add B to each 2D array slice of A.
* Print the result

####5. : You are given a grayscale image of shape (32, 32), where each pixel value is an integer. You want to apply a scaling factor of 0.5 to all the pixel values using broadcasting.


* Use broadcasting to scale the image by multiplying it with the scaling factor 0.5.
* Verify that the pixel values of the image are halved by printing the scaled image.

####6. Calculate the distance between an observation point and a set of code points (codes). The goal is to find the closest code to the observation by calculating the Euclidean distance between each code and the observation.

* Given two arrays :

codes = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [1.0, 1.0, 1.0],
    [2.0, 3.0, 4.0]
])


observation = np.array([3.0, 3.0, 3.0])


* Use broadcasting to calculate the squared Euclidean distance between the observation and each code.
* Find and print the index of the closest code to the observation.
* Print the distance between the observation and the closest code.

**HINT : use np.argmin() to find the index of the closest code**




In [76]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])
C=A+B
print(C,C.shape)

#The resulting shape is (3,3)

[[11 22 33]
 [14 25 36]
 [17 28 39]] (3, 3)


In [77]:
def check_broadcasting(shape1, shape2):
  aShape=np.array(shape1)
  bShape=np.array(shape2)
  while aShape.shape != bShape.shape :
    if aShape.shape > bShape.shape:
      bShape=np.append(1,bShape)
    else:
      aShape=np.append(1,aShape)

  for i,j in zip(aShape,bShape):
    if i!=j and i!=1 and j!=1:
      print(shape1,shape2,"Not Possible")
      return None

  print(shape1,shape2,"Possible")
  aShape[aShape==1]=0
  bShape[bShape==1]=0

  Shape=aShape|bShape
  print("shape:",Shape)

check_broadcasting((3,4), (4,))
check_broadcasting((2,1,5), (3,5))
check_broadcasting((2,3), (2,))

(3, 4) (4,) Possible
shape: [3 4]
(2, 1, 5) (3, 5) Possible
shape: [2 3 5]
(2, 3) (2,) Not Possible


In [78]:
A=np.random.randint(1,10,size=(3,5))
B=np.random.randint(1,5,size=(5,))
C=A-B
print(A)
print(B)
print(C)

[[6 2 2 4 8]
 [7 9 8 5 2]
 [5 8 9 9 1]]
[1 3 1 4 1]
[[ 5 -1  1  0  7]
 [ 6  6  7  1  1]
 [ 4  5  8  5  0]]


In [79]:
# 4. Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10.
# Create an array B of shape (4, 3) containing a constant value of 5.
# Use broadcasting to add B to each 2D array slice of A.
# Print the result

A=np.random.randint(0,10,size=(2,4,3))
B=np.tile(5,(4,3))
C=A+B
# print(A)
print(C)

[[[12 12  7]
  [ 5 12  7]
  [ 7  5  9]
  [14 11 14]]

 [[13 11 13]
  [12  6  5]
  [11 11 12]
  [ 9  7 12]]]


In [80]:
# 5. : You are given a grayscale image of shape (32, 32), where each pixel value is an integer. You want to apply a scaling factor of 0.5 to all the pixel values using broadcasting.
# Use broadcasting to scale the image by multiplying it with the scaling factor 0.5.
# Verify that the pixel values of the image are halved by printing the scaled image.
img=np.random.randint(0,255,size=(32,32))
print(img)
img=(img*0.5).astype(int)
print(img)

[[213 218  34 ...  51 252  95]
 [131 221 228 ...  29 189  74]
 [127 249 246 ... 206  58 117]
 ...
 [221 221 250 ... 190 225  51]
 [248 165 224 ... 234  42 239]
 [202 114 110 ...   4 209  91]]
[[106 109  17 ...  25 126  47]
 [ 65 110 114 ...  14  94  37]
 [ 63 124 123 ... 103  29  58]
 ...
 [110 110 125 ...  95 112  25]
 [124  82 112 ... 117  21 119]
 [101  57  55 ...   2 104  45]]


In [81]:
# 6.Calculate the distance between an observation point and a set of code points (codes). The goal is to find the closest code to the observation by calculating the Euclidean distance between each code and the observation.
# Given two arrays :
# codes = np.array([ [1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [1.0, 1.0, 1.0], [2.0, 3.0, 4.0] ])

# observation = np.array([3.0, 3.0, 3.0])

# Use broadcasting to calculate the squared Euclidean distance between the observation and each code.
# Find and print the index of the closest code to the observation.
# Print the distance between the observation and the closest code.
# HINT : use np.argmin() to find the index of the closest code

codes = np.array([ [1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [1.0, 1.0, 1.0], [2.0, 3.0, 4.0] ])
observation = np.array([3.0, 3.0, 3.0])

Dist=np.sqrt(np.sum((codes-observation)**2,axis=1))
closestIdx=np.argmin(Dist)
print(closestIdx)
print(Dist[closestIdx])

4
1.4142135623730951


# **Concatenation**

1. Write a program to vertically stack arrays using `np.vstack` and print the result: (Use any three 1D arrays) <br/>
<br/>
2. Write a program to horizontally stack arrays using `np.hstack`. Print the result: (Use any three 1D arrays) <br/>
<br/>
3. Given two 2D arrays of the same row size, horizontally stack them using `np.hstack` and print the result:<br/>
`m = np.array([[2, 4], [3, 6]])`<br/>
`n = np.array([[4, 8], [5, 10]])`<br/>
<br/>
4. Using `np.vstack`, stack the following arrays vertically and print the results:<br/>
`a = np.array([11, 12, 13])`<br/>
`b = np.array([[14, 15, 16], [17, 18, 19]])`<br/>
<br/>
5. Concatenate the following 2D arrays along different axes using `np.concatenate`. Demonstrate how to concatenate them along axis 0 and axis 1.<br/>
`x = np.array([[1, 2], [3, 4]])`<br/>
`y = np.array([[5, 6], [7, 8]])`<br/>
`z = np.array([[9, 10], [11, 12]])`<br/>

In [82]:
a=np.ones(5)
b=np.zeros(5)
c=np.arange(5)
d=np.vstack((a,b,c))
print(d)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]]


In [83]:
a=np.ones((5,1))
b=np.zeros((5,1))
c=np.random.randint(1,10,size=(5,1))
d=np.hstack((a,b,c))
print(d)

[[1. 0. 6.]
 [1. 0. 5.]
 [1. 0. 6.]
 [1. 0. 1.]
 [1. 0. 5.]]


In [84]:
m = np.array([[2, 4], [3, 6]])
n = np.array([[4, 8], [5, 10]])
o=np.hstack((m,n))
print(o)

[[ 2  4  4  8]
 [ 3  6  5 10]]


In [85]:
a = np.array([11, 12, 13])
b = np.array([[14, 15, 16], [17, 18, 19]])
c=np.vstack((a,b))
print(c)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [86]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.array([[9, 10], [11, 12]])
h=np.concatenate((x,y,z),axis=1)
v=np.concatenate((x,y,z),axis=0)
print(h)
print(v)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# Boolean Masking

1. Use Boolean masking to filter elements from a 1D array:
Write a program to create a 1D array and use Boolean masking to filter out all elements greater than 5.<br/>

2. Apply a Boolean mask to a 2D array:
Given the 2D array below, create a Boolean mask to select all elements greater than 10 and print the masked elements.<br/>
`arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])`
 <br/>
3. Create a Boolean mask using a condition on an array:
Create a 1D array of integers from 0 to 10. Use a Boolean mask to filter out all even numbers and print the result.<br/>
Example:
`arr = np.arange(11)`
<br/>
4. Combine Boolean masks using logical operations:
Given the array below, create and combine two Boolean masks:<br/>
One mask selects elements greater than 5.
The other mask selects elements divisible by 3.
Combine the masks using logical AND and print the result.
Example:
`arr = np.array([1, 3, 6, 9, 12, 15])`
<br/>
5. Mask elements in a 2D array and replace them:
Write a program to replace all elements less than 5 in the 2D array below with 0 using Boolean masking.
<br/>
6.  Count elements satisfying a condition using Boolean masks:
Write a program to count how many elements in the array below are greater than 5.
<br/>

In [87]:
arr=np.random.randint(1,10,size=10)
mask=arr<=5
print(arr[mask])

[2 1 1 4]


In [88]:
arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])
mask=arr>10
print(arr[mask])

[12 18 11 14]


In [89]:
arr = np.arange(11)
mask=arr%2!=0
print(arr[mask])

[1 3 5 7 9]


In [90]:
arr=np.array([1, 3, 6, 9, 12, 15])
mask1=arr>5
mask2=arr%3==0
mask=np.logical_and(mask1,mask2)
print(arr[mask])

[ 6  9 12 15]


In [91]:
arr=np.random.randint(1,8,size=(4,4))
print("pre:\n",arr)
mask=arr<5
arr[mask]=0
print("post:\n",arr)

pre:
 [[1 1 3 5]
 [4 7 7 7]
 [6 6 2 4]
 [7 6 2 5]]
post:
 [[0 0 0 5]
 [0 7 7 7]
 [6 6 0 0]
 [7 6 0 5]]


In [92]:
arr=np.random.randint(1,8,size=(4,4))
mask=arr<5
count=np.sum(mask)
print(arr)
print(count)


[[2 6 3 3]
 [7 3 7 7]
 [6 3 7 4]
 [5 2 2 6]]
8
